name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: "JDK ${{ matrix.java }}"
    strategy:
      matrix:
        java: [ 8, 11 ]
    runs-on: ubuntu-latest
    env:
      # Not actually used since we aren't building/testing the Android version,
      # but Maven still needs an absolute path or it complains.
      ANDROID_HOME: /
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - name: 'Cache local Maven repository'
        uses: actions/cache@v2.1.4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - name: 'Set up JDK ${{ matrix.java }}'
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: 'Install'
        shell: bash
        run: mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn install -U -DskipTests=true -am -pl caliper
      - name: 'Test'
        shell: bash
        run: mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean verify -U -Dmaven.javadoc.skip=true -am -pl caliper
